import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — Glance',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background text-foreground px-6 py-12 max-w-2xl mx-auto">
      <nav className="mb-10">
        <Link href="/" className="font-serif italic text-xl wordmark">Glance.</Link>
      </nav>

      <h1 className="text-2xl font-serif italic mb-1">Terms of Service</h1>
      <p className="text-xs text-muted mb-8">Last updated: June 5, 2025</p>

      <div className="space-y-8 text-sm leading-relaxed text-foreground">

        <section>
          <h2 className="font-medium mb-2">1. Acceptance of Terms</h2>
          <p className="text-muted">
            By creating an account or using Glance ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="font-medium mb-2">2. Description of Service</h2>
          <p className="text-muted">
            Glance delivers AI-generated daily summaries of stock market news and commentary relevant to portfolios you configure ("Digest"). The Service may also include stock predictions, sentiment analysis, and other informational content. Glance is a personal information tool — it is not a brokerage, financial advisor, or investment platform.
          </p>
        </section>

        <section>
          <h2 className="font-medium mb-2">3. Investment Disclaimer</h2>
          <p className="text-muted">
            <strong className="text-foreground">Nothing on Glance constitutes financial, investment, legal, or tax advice.</strong> All content is for informational and educational purposes only. Glance is not a registered investment advisor. Stock predictions and analysis are generated by AI models and may be inaccurate, incomplete, or outdated. Past performance of any stock or prediction does not guarantee future results. You are solely responsible for any investment decisions you make. Always consult a qualified financial professional before making investment decisions.
          </p>
        </section>

        <section>
          <h2 className="font-medium mb-2">4. Your Account</h2>
          <p className="text-muted">
            You are responsible for maintaining the security of your account. You may only use the Service for lawful, personal purposes. You may not share account access or use the Service on behalf of a third party without our written permission.
          </p>
        </section>

        <section>
          <h2 className="font-medium mb-2">5. Prohibited Uses</h2>
          <p className="text-muted mb-2">You may not:</p>
          <ul className="text-muted list-disc list-inside space-y-1">
            <li>Scrape, copy, or redistribute Glance content for commercial purposes</li>
            <li>Use Glance output to feed automated trading systems without our written consent</li>
            <li>Attempt to reverse-engineer or interfere with the Service</li>
            <li>Use the Service in any way that violates applicable law</li>
          </ul>
        </section>

        <section>
          <h2 className="font-medium mb-2">6. Intellectual Property</h2>
          <p className="text-muted">
            All content, branding, and software comprising the Service is owned by or licensed to Glance. You are granted a limited, non-exclusive, non-transferable license to use the Service for personal use. Nothing in these Terms transfers ownership of any Glance intellectual property to you.
          </p>
        </section>

        <section>
          <h2 className="font-medium mb-2">7. Limitation of Liability</h2>
          <p className="text-muted">
            To the fullest extent permitted by law, Glance and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to investment losses, lost profits, or decisions made in reliance on Glance content. The Service is provided "as is" without warranties of any kind.
          </p>
        </section>

        <section>
          <h2 className="font-medium mb-2">8. Service Availability</h2>
          <p className="text-muted">
            We do not guarantee uninterrupted access to the Service. We may suspend or discontinue features at any time without notice. Digests are delivered on a best-effort basis; we are not liable for missed or delayed delivery.
          </p>
        </section>

        <section>
          <h2 className="font-medium mb-2">9. Changes to These Terms</h2>
          <p className="text-muted">
            We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated Terms. We will make reasonable efforts to notify registered users of material changes.
          </p>
        </section>

        <section>
          <h2 className="font-medium mb-2">10. Contact</h2>
          <p className="text-muted">
            Questions about these Terms? Email us at{' '}
            <a href="mailto:support@glance.so" className="text-foreground underline underline-offset-2">support@glance.so</a>.
          </p>
        </section>

      </div>

      <div className="mt-12 pt-6 border-t border-border flex gap-4 text-xs text-muted">
        <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</Link>
        <Link href="/" className="hover:text-foreground transition-colors">Back to Glance</Link>
      </div>
    </main>
  )
}
